apiVersion: simple-trace-db.odigos.io/v1
kind: Query
metadata:
  name: parent-child
  description: |
    TODO
spec:
  query: |
    length([?(
      span.resourceAttributes."odigos.version" == 'e2e-test' &&
      span.resourceAttributes."telemetry.sdk.language" == 'java' &&
      span.serviceName == 'frontend' &&
      span.kind == 'server' &&
      span.spanAttributes."http.request.method" == 'POST' &&
      span.spanAttributes."http.response.status_code" == `200` &&
      span.spanAttributes."http.route" == '/buy' &&
      span.spanAttributes."url.query" == 'id=123'
    )]) > `0`

    && 

    length([?(
      span.resourceAttributes."odigos.version" == 'e2e-test' &&
      span.resourceAttributes."telemetry.sdk.language" == 'dotnet' &&
      span.serviceName == 'pricing' &&
      span.kind == 'server'
    )]) > `0`

    &&

    length([?(
      span.resourceAttributes."odigos.version" == 'e2e-test' &&
      span.resourceAttributes."telemetry.sdk.language" == 'python' &&
      span.serviceName == 'inventory' &&
      span.kind == 'server'
    )]) > `0`

    && 

    length([?(
      span.resourceAttributes."odigos.version" == 'e2e-test' &&
      span.resourceAttributes."telemetry.sdk.language" == 'nodejs' &&
      span.serviceName == 'coupon' &&
      span.kind == 'server'
    )]) > `0`

    &&

    length([?(
      span.resourceAttributes."odigos.version" == 'e2e-test' &&
      span.resourceAttributes."telemetry.sdk.language" == 'go' &&
      span.serviceName == 'membership' &&
      span.kind == 'server'
      span.spanAttributes."http.request.method" == 'GET' &&
      span.spanAttributes."http.response.status_code" == `200` &&
      span.spanAttributes."url.path" == '/isMember'
    )]) > `0`
  querySyntax: JMESPath
  spansStructure: ReverseTree
