name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  release:
    runs-on: depot-ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - id: gcp-auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 1200s
  
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  
  
      - name: Build and Push Docker Image for simple-trace-db
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            us-central1-docker.pkg.dev/odigos-cloud/components/simple-trace-db:${{ steps.release.outputs.version }}
            ghcr.io/${{ github.repository }}/simple-trace-db:${{ steps.release.outputs.version }}
            registry.depot.dev/84dl6xf069:simple-trace-db
          platforms: linux/amd64,linux/arm64
        