name: Prepare Release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  release-job:
    runs-on: depot-ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get release token
        uses: odigos-io/ci-core/sts@main
        id: release-token
        with:
          pairs: |
            odigos-io/simple-trace-db:releaser

      - name: Create or Update Release PR
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.release-token.outputs.GH_TOKEN }}
